def press(s):
    t1.insert(len(t1.get()),s)
def calc():
    try:
        s=eval(t1.get())
        t2.delete(0,len(t2.get()))
        t2.insert(0,s)
    except ZeroDivisionError:
        t2.delete(0,len(t2.get()))
        t2.insert(0,'Cant Divide By Zero')
    except:
        t2.delete(0,len(t2.get()))
        t2.insert(0,'Invalid Input')
def clr():
    t1.delete(0,len(t1.get()))
    t2.delete(0,len(t2.get()))
def back():
    t2.delete(0,len(t2.get()))
    n=t1.get()
    t1.delete(0,len(t1.get()))
    n=n[:-1]
    t1.insert(0,n)
from tkinter import *
w=Tk()
w.title("Dhanush's Calculator")
t1=Entry(w,width=40)
t2=Entry(w,width=40)
bcal=Button(w,text='Calculate',width=33,command=calc)
t1.grid(row=0,column=0)
bcal.grid(row=2,column=0)
t2.grid(row=1,column=0)
bclr=Button(w,text='Clear',width=33,command=clr)
bclr.grid(row=3,column=0)
b1=Button(w,text='1',width=5,command=lambda:press('1'))
b1.grid(row=0,column=2)
b2=Button(w,text='2',width=5,command=lambda:press('2'))
b2.grid(row=0,column=3)
b3=Button(w,text='3',width=5,command=lambda:press('3'))
b3.grid(row=0,column=4)
b4=Button(w,text='4',width=5,command=lambda:press('4'))
b4.grid(row=1,column=2)
b5=Button(w,text='5',width=5,command=lambda:press('5'))
b5.grid(row=1,column=3)
b6=Button(w,text='6',width=5,command=lambda:press('6'))
b6.grid(row=1,column=4)
b7=Button(w,text='7',width=5,command=lambda:press('7'))
b7.grid(row=2,column=2)
b8=Button(w,text='8',width=5,command=lambda:press('8'))
b8.grid(row=2,column=3)
b9=Button(w,text='9',width=5,command=lambda:press('9'))
b9.grid(row=2,column=4)
b0=Button(w,text='0',width=5,command=lambda:press('0'))
b0.grid(row=3,column=3)
bs=Button(w,text='<|--',width=5,command=back)
bs.grid(row=3,column=2)
bp=Button(w,text='.',width=5,command=lambda:press('.'))
bp.grid(row=3,column=4)
badd=Button(w,text='+',width=5,command=lambda:press('+'))
badd.grid(row=0,column=5)
bsub=Button(w,text='-',width=5,command=lambda:press('-'))
bsub.grid(row=1,column=5)
bmul=Button(w,text='*',width=5,command=lambda:press('*'))
bmul.grid(row=2,column=5)
bdiv=Button(w,text='/',width=5,command=lambda:press('/'))
bdiv.grid(row=3,column=5)
l1=Label(w,text='Use ** For Exponential Operation')
l1.grid(row=0,column=6)
l2=Label(w,text='Press <|-- For Back Space')
l2.grid(row=1,column=6)
